version: '3.8'

services:
  # MariaDB Database
  mariadb:
    image: 'mariadb:latest'
    container_name: mariadb-instalite
    restart: always
    environment:
      - 'MARIADB_DATABASE=instalite'
      - 'MARIADB_PASSWORD=root'
      - 'MARIADB_ROOT_PASSWORD=root'
      - 'MARIADB_USER=root'
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql

  # Vue Frontend
  vue-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vue-instalite
    ports:
      - "4200:8080"

  # Check if the database is ready
  check-db:
    image: jwilder/dockerize:latest
    depends_on:
      - mariadb
    command: 'dockerize -wait tcp://mariadb:3306 -timeout 120s'

  # Spring Boot Backend
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-instalite
    ports:
      - "8080:8080"
    depends_on:
      - check-db
    volumes:
      - ./storage:/app/storage

volumes:
  mariadb-data:
