version: '3'

services:
  spring-app:
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/instalite
      SPRING_DATASOURCE_USERNAME: gil
      SPRING_DATASOURCE_PASSWORD: m2gilunivrouen
    volumes:
      - myapp-volume:/opt/app/data

  mariadb:
    image: mariadb:latest
    environment:
      MARIADB_DATABASE: instalite
      MARIADB_USER: gil
      MARIADB_PASSWORD: m2gilunivrouen
      MARIADB_ROOT_PASSWORD: verysecret
    ports:
      - '3306:3306'
    volumes:
      - mariadb-volume:/var/lib/mysql

volumes:
  myapp-volume:
  mariadb-volume:
